#!/usr/bin/python
import sys
import subprocess


def mp3_320ize(filename):
    print subprocess.check_output([
        "ffmpeg",
        "-i", filename,
        "-ab", "320k",
        filename[:filename.rfind(".")] + ".mp3"
    ])


if __name__ == '__main__':
    if len(sys.argv) < 1:
        print "Tell me which file(s)."
    else:
        for f in sys.argv[1:]:
            mp3_320ize(f)
