#!/usr/bin/env python
import argparse
import subprocess
from pathlib import Path


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("file", nargs="+")
    args = parser.parse_args(argv)

    for file in args.file:
        subprocess.run(
            [
                "ffmpeg",
                "-i",
                file,
                "-ab",
                "320k",
                str(Path(file).with_suffix(".mp3")),
            ],
            check=True,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
