#!/usr/bin/python
import sys
import subprocess


def run_and_get_output(comm):
        return subprocess.Popen(comm, stdout=subprocess.PIPE).communicate()[0]


def audio_dump(filename):
    run_and_get_output(["ffmpeg", "-i", filename, "-acodec", "copy", filename[:-4] + ".mp3"])

if __name__ == '__main__':
    if len(sys.argv) < 1:
        print "Tell me which file(s)."
    else:
        for f in sys.argv[1:]:
            audio_dump(f)
