#!/bin/bash
# By djchainz
# Licensed under the GNU GPL 2.0
#Set up
scriptname="FlashSwap"

#Must run as root
if [ "`whoami`" != "root" ];
then
	zenity --error --title=$scriptname --text='You must run this as root; try using sudo.'
	exit
fi

#Check one is not currently in use by script
uuid="`cat ${HOME}/.$scriptname/disk`"
diskpath="/dev/disk/by-uuid/`readlink /dev/disk/by-uuid/$uuid`"
diskpath="`basename $diskpath`"
if [ "`cat /proc/swaps | grep $diskpath`" = "" ]
then
	uuid=""
	rm ${HOME}/.$scriptname/disk
	rm -r ${HOME}/.$scriptname
fi

#If one is... offer to unmount and exit whether or not
if [ "$uuid" != "" ]
then
	text="You are already using a disk (uuid $uuid) with $scriptname. Do you want to stop using it?"
	if zenity --question --title=$scriptname --text="$text"
	then
		swapoff /dev/disk/by-uuid/$uuid
		rm ${HOME}/.$scriptname/disk
		rm -r ${HOME}/.$scriptname
		zenity --info --title=$scriptname --text="The swap has been stopped.  Run again to use another drive."
	fi
	exit
fi

#Find possible "sd" partitions to swapon
drives="`ls -1 /dev/sd* | egrep /dev/sd[a-z]+[0-9]+`"
for d in $drives
do
	#Only those which are of type swap
	if [ "`vol_id -t $d`" = "swap" ]
	then
		#And currently don't have swap on them
		if [ "`cat /proc/swaps | grep $d`" = "" ]
		then
			drives2="$drives2 $d";
		fi
	fi
done

#If we have no plausible partitions
if [ "`echo -n $drives2`" = "" ]
then
	zenity --error --title=$scriptname --text='No unused swap partition was found.  Please insert the disk and/or make a swap partition on your disk of choice by using Gnome Partition Editor - gparted. This will now exit.'
	#perhaps here offer to wipe a disk drive
	exit
fi

#We do have plausible partitions
drives2="`echo $drives2 | sed 's/\/dev\//False \/dev\//g'`"
result="`zenity --list --title=$scriptname --text='You have unused swap partitions; select one to use:' --radiolist --column=On --column=Drive $drives2 `"
#If they chose one
if [ $result ]; then
	#swapon it!
	uuid="`vol_id -u $result`"
	swapon -p 32767 -U	$uuid
	#Store in config file for later
	mkdir -p ${HOME}/.$scriptname/
	echo $uuid > ${HOME}/.$scriptname/disk
	#WARN THEM
	zenity --info --title=$scriptname --text='Swap is now on that drive with top priority.  Do NOT remove the drive until you have run this program again to eject it!!'
fi