#!/bin/sh
AUTHOR=$1
SINCE=$2
if [[ "$SINCE" = "" ]]; then
    SINCE="1970"
fi
UNTIL=$3
if [[ "$UNTIL" = "" ]]; then
    UNTIL="today"
fi
echo For $AUTHOR since $SINCE until $UNTIL:
git rev-list --all --since="$SINCE" --until="$UNTIL" --author="$AUTHOR" | wc -l
