#!/bin/sh
AUTHOR=$1
SINCE=$2
if [[ "$SINCE" = "" ]]; then
    SINCE="1970"
fi
UNTIL=$3
if [[ "$UNTIL" = "" ]]; then
    UNTIL="today"
fi
echo For $AUTHOR since $SINCE until $UNTIL:
git log --since="$SINCE" --until="$UNTIL" --author="$AUTHOR" --pretty=tformat: --numstat | gawk '{ add += $1 ; subs += $2 ; sum += $1 + $2; net += $1 - $2; } END { printf "Added lines: %s, Removed lines : %s, Total lines affected: %s, Net: %s\n",add,subs,sum,net }' -
