#!/bin/sh
echo "this is just a list of useful commands! open it up"
exit

git log --shortstat --format=format:"%cd" --date=short --no-merges | sed -e '/^$/d;N;s/\n//;s/files changed, //;s/insertions(+), //;s/ deletions(-)//'

# just delta info:
git log --shortstat --format=format:"" --no-merges --all | sed '/^$/d;s/[a-z()+,-]//g'

# num commits total
git log --format=format:"%cd" --date=short --no-merges --all | wc -l

# num commits for each day
git log --format=format:"%cd" --date=short --no-merges --all | uniq -c

# avg commits per day
git log --format=format:"%cd" --date=short --no-merges --all | uniq -c | awk '{ total += $1; count++ } END { print total/count }'

# num commits in each 24 hour slot
git log --format=format:"%cd" --no-merges --all | tr ':' ' ' | awk '{print $4}' | sort | uniq -c

# num commits by day of the week
git log --format=format:"%cd" --no-merges --all | awk '{print $1}' | sort | uniq -c
