#!/bin/zsh
set -ex
if [ -n "$1" ]; then
    branch_name=$1
else
    branch_name=$(git rev-parse --abbrev-ref HEAD)
    if [ "$branch_name" = "master" ]; then
        echo "Pass the branch name"
        exit 1
    fi
fi

if git rev-parse --verify master >/dev/null 2>&1; then
    base_branch='master'
elif git rev-parse --verify develop >/dev/null 2>&1; then
    base_branch='develop'
else
    echo "branches master and develop don't exist, can't figure base branch"
    exit 1
fi

git diff --exit-code
git checkout $base_branch
git merge --ff-only "$branch_name"
git push
git branch -d "$branch_name"
git push origin :"$branch_name"
