#!/bin/zsh
set -ex
if [ -n "$1" ]; then
    branch_name=$1
else
    branch_name=$(git rev-parse --abbrev-ref HEAD)
    if [ "$branch_name" = "master" ]; then
        echo "Pass the branch name"
        exit 1
    fi
fi

git diff --exit-code
git checkout master
git ffmerge "$branch_name"
git push
git branch -d "$branch_name"
git push origin :"$branch_name"
