#!/usr/bin/python
# coding=utf-8
import sys
from datetime import datetime, date
from django.utils.termcolors import make_style

# Styles
if sys.stdout.isatty():
    bold = make_style(fg='yellow', opts=('bold',))
    redbold = make_style(fg='red', opts=('bold',))
else:
    bold = redbold = lambda x:x

# Calc
birthday = date(1989, 10, 4)
today = datetime.utcnow().date()

day_num = (today - birthday).days

expected = 28506

remaining = expected - day_num
percentage = "%0.2f" % ((day_num / float(expected)) * 100)

print ""
print bold("Hello Adam,"), "you have been alive", redbold("%i days" % day_num), "and you are projected to live", redbold("%i more" % remaining) + ". " + bold("(" + percentage + "%)")
print ""
