#!/usr/bin/env python3
# coding=utf-8
import sys
from datetime import datetime, date

# Styles
if sys.stdout.isatty():
    def bold(text):
        return '\x1b[33;1m' + text + '\x1b[0m'

    def redbold(text):
        return '\x1b[31;1m' + text + '\x1b[0m'
else:
    bold = redbold = lambda text: text

def main():
    birthday = date(1989, 10, 4)
    today = datetime.utcnow().date()

    day_num = (today - birthday).days

    expected = 28506

    remaining = expected - day_num
    percentage = "%0.2f" % ((day_num / float(expected)) * 100)

    sys.stdout.write(
        "\n" +
        bold("Hello Adam, ") +
        "you have been alive " +
        redbold("{} days ".format(day_num)) +
        "and you are projected to live " +
        redbold("{} more. ".format(remaining)) +
        bold("({}%)".format(percentage)) +
        "\n\n"
    )

if __name__ == '__main__':
    main()
