#!/usr/bin/python
import os
import sys
import subprocess


def run_and_get_output(comm):
        return subprocess.Popen(comm, stdout=subprocess.PIPE).communicate()[0]


def pngcrush_one(filename):
    sys.stdout.write("Crushing " + filename + "...")
    sys.stdout.flush()

    size_before = os.path.getsize(filename)

    run_and_get_output(["pngcrush", filename, "/tmp/tmp.png"])
    run_and_get_output(["mv", "/tmp/tmp.png", filename])
    run_and_get_output(["chmod", "755", filename])

    size_after = os.path.getsize(filename)

    percentage = "{0:.0f}%".format(float(size_after) / size_before * 100)
    print "Crushed, from %i to %i" % (size_before, size_after), "(%s)" % percentage


def pngcrush_all_recursive():
    png_files = []
    for root, dirs, files in os.walk('./'):
        for name in [f for f in files if f.endswith(".png")]:
            png_files.append(os.path.join(root, name))
    for f in png_files:
        pngcrush_one(f)


if __name__ == '__main__':
    if not len(sys.argv) > 1:
        print "Tell me which files, or --all for recursive all."
    else:
        if sys.argv[1] == "--all":
            pngcrush_all_recursive()
        else:
            # Individual named files
            for f in sys.argv[1:]:
                pngcrush_one(f)
