#!/bin/zsh
set -ex
if [[ ! -d requirements ]]; then
    echo "Need requirements/"
    exit 1
fi
git diff --exit-code
git checkout master
git pull
git checkout -b upgrade_requirements
cd requirements || exit 1
./compile.sh --upgrade
cd .. || exit 1
git add --all
git commit -m 'Upgrade requirements'
git push -u origin upgrade_requirements
hub pull-request -F - -o <<< "Upgrade requirements"
