#!/bin/zsh
set -ex
if [[ ! -d requirements ]]; then
    echo "Need requirements/"
    exit 1
fi
git diff --exit-code
git checkout master
git pull
git checkout -b upgrade_requirements
./requirements/compile.py --upgrade
git add --all
git commit -m 'Upgrade requirements'
git push -u origin upgrade_requirements
gh pr create --fill
gh pr view --web
