#!/usr/bin/env python3
import subprocess
import sys


def main():
    branch_name = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], universal_newlines=True).strip()
    subprocess.check_output(['git', 'push', '-u', 'origin', branch_name])
    try:
        remote_url = subprocess.check_output(['git', 'remote', 'get-url', 'origin'], universal_newlines=True).strip()
    except subprocess.CalledProcessError:
        print("Couldn't get remote 'origin'", file=sys.stderr)
        sys.exit(0)

    who_at_where, repo_git_name = remote_url.split(':')
    if who_at_where != 'git@github.com':
        print(f"Remote URL {remote_url} isn't a github url", file=sys.stderr)
        sys.exit(0)
    repo_name = repo_git_name[:-len('.git')]
    print(repo_name)

    make_pr_url = f'https://github.com/{repo_name}/compare/{branch_name}?expand=1'
    subprocess.check_output(['open', make_pr_url])


if __name__ == '__main__':
    main()
