#!/bin/sh
set -e

version=$1

if [ "$version" = "" ]; then
    echo "Usage: py-release version"
    exit 1
fi

git diff --exit-code
git checkout master
git pull

sd 'version = .*' "version = $version" setup.cfg
date=$(date '+%Y-%m-%d' | tr -d '\n')
versionline="$version ($date)"
# shellcheck disable=SC2039
underline=$(printf -- '-%.0s' {1..${#versionline}})

sd -f m '(=======
History
=======)' "\$1

$versionline
$underline" HISTORY.rst

git add setup.cfg HISTORY.rst
git commit -m "Version $version"

rm -rf build dist src/*.egg-info
PIP_REQUIRE_VIRTUALENV='' python -m build
twine check dist/*
twine upload --sign dist/*

git push origin master
git tag "$version"
git push --tags origin "$version"
