#!/bin/bash
set -e
name=$(basename "$PWD").sublime-project
if [ -e "$name" ]; then
    echo "$name already exists!" >&2
    exit 1
fi
echo '{
    "folders": [
        {
            "path": ".",
            "file_exclude_patterns": [
                ".coverage*",
                "*.pyc"
            ],
            "folder_exclude_patterns": [
                "*.cache",
                "*.egg-info",
                ".egg",
                ".mypy_cache",
                ".nox",
                ".pytest_cache",
                ".tox",
                "__pycache__",
                "build",
                "dist",
                "htmlcov",
                "venv"
            ],
        }
    ],
    "settings": {
        "rulers": [79, 119],
    }
}' > "$name"
open "$name"
