#!/bin/bash
set -e
name=$(basename "$PWD").sublime-project
if [ -e "$name" ]; then
    echo "$name already exists!" >&2
    exit 1
fi
echo '{
    "folders": [
        {
            "path": ".",
            "file_exclude_patterns": [
                "*.pyc"
            ],
            "folder_exclude_patterns": [
                ".tox"
            ],
        }
    ],
    "settings": {
        "rulers": [79, 119],
    }
}' > "$name"
open "$name"
