#!/bin/bash
#arg1 : image
#arg2 : audio file (mp3)
#arg3 : output flv
if [ $# -ne 3 ]; then
	echo 1>&2 Usage: image audio file outputvideo
	exit 127
fi

duration=`ffmpeg -i $2 2>&1 | egrep Duration | sed 's/\s\sDuration:\s//' | sed 's/,.*//'`
ffmpeg -loop_input -i $1 -i $2 -r 1 -b 1400k -acodec copy -t $duration $3